apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myportfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyohmizu/k8s-mycluster.git
    targetRevision: HEAD
    path: apps/myportfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
