---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio
  labels:
    app: myportfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myportfolio
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
      - name: myportfolio
        image: kyohmizu/myportfolio:83e2e49c45ec2d7670d3340d5a3dc2c35b96aa33
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myportfolio
  name: myportfolio
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myportfolio
