name: automerge develop and pull request to master

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches:
      - develop
  pull_request_review:
    types:
      - submitted
    branches:
      - develop
  check_suite:
    types:
      - completed
    branches:
      - develop

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install hub
        uses: geertvdc/setup-hub@v1.0.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        env:
          REVIEWERS: "kyohmizu"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: develop
        run: |
          hub pull-request -m "Pull Request from Github Actions" -b master -h $BRANCH_NAME -r "$REVIEWERS" -l automerge
