name: automerge and pull request

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  dump_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'develop'
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  pull_request:
    needs: automerge
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'develop'
    steps:
      - name: Install hub
        uses: geertvdc/setup-hub@v1.0.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        env:
          REVIEWERS: "kyohmizu"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: develop
        run: |
          hub pull-request -m "Pull Request from Github Actions" -b master -h $BRANCH_NAME -r "$REVIEWERS" -l automerge
