name: Pull Request to master when merged

on:
  pull_request:
    types:
      - closed

jobs:
  dump_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  pull_request:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        env:
          REVIEWERS: "kyohmizu"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: develop
        run: |
          hub pull-request -m "Pull Request from Github Actions" -b master -h $BRANCH_NAME -r "$REVIEWERS" -l automerge
